/*
 * Copyright 2012 The Netty Project
 *
 * The Netty Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

using System;
using System.Buffers;
using System.Globalization;
using System.Text;
using Netty.NET.Common.Internal;

namespace Netty.NET.Buffer;

public static partial class ByteBufUtil
{
/**
     * Returns a <a href="https://en.wikipedia.org/wiki/Hex_dump">hex dump</a>
     * of the specified buffer's readable bytes.
     */
    public static string HexDump(ByteBuf buffer)
    {
        ArgumentNullException.ThrowIfNull(buffer);
        return HexDump(buffer, buffer.ReaderIndex, buffer.ReadableBytes);
    }

/**
     * Returns a <a href="https://en.wikipedia.org/wiki/Hex_dump">hex dump</a>
     * of the specified buffer's sub-region.
     */
    /// <remarks>The range is absolute and may extend beyond WriterIndex up to Capacity.
    /// No indices change. Buffer lifetime and content must remain stable during formatting.</remarks>
    public static string HexDump(ByteBuf buffer, int fromIndex, int length)
    {
        ArgumentNullException.ThrowIfNull(buffer);
        ReadOnlySequence<byte> sequence = buffer.AsReadOnlySequence(fromIndex, length);
        int characters = checked(length * 2);
        if (sequence.IsSingleSegment) return HexDump(sequence.FirstSpan);
        return string.Create(characters, sequence, static (destination, bytes) =>
        {
            const string digits = "0123456789abcdef";
            int i = 0;
            foreach (ReadOnlyMemory<byte> segment in bytes)
                foreach (byte value in segment.Span)
                {
                    destination[i++] = digits[value >> 4];
                    destination[i++] = digits[value & 15];
                }
        });
    }

/**
     * Returns a <a href="https://en.wikipedia.org/wiki/Hex_dump">hex dump</a>
     * of the specified byte array.
     */
    public static string HexDump(byte[] array)
    {
        ArgumentNullException.ThrowIfNull(array);
        return HexDump(array.AsSpan());
    }

/**
     * Returns a <a href="https://en.wikipedia.org/wiki/Hex_dump">hex dump</a>
     * of the specified byte array's sub-region.
     */
    public static string HexDump(byte[] array, int fromIndex, int length)
    {
        ArgumentNullException.ThrowIfNull(array);
        CheckHexRange(array.Length, fromIndex, length);
        return HexDump(array.AsSpan(fromIndex, length));
    }

    /// <summary>Formats every octet as two lowercase ASCII hex digits without separators.</summary>
    public static string HexDump(ReadOnlySpan<byte> bytes) => Convert.ToHexStringLower(bytes);

/**
     * Decode a 2-digit hex byte from within a string.
     */
    public static byte DecodeHexByte(string text, int position) => StringUtil.DecodeHexByte(text, position);

    /// <summary>Decodes exactly two ASCII hex digits at the specified character position.</summary>
    public static byte DecodeHexByte(ReadOnlySpan<char> text, int position)
    {
        CheckHexRange(text.Length, position, 2);
        int hi = StringUtil.DecodeHexNibble(text[position]);
        int lo = StringUtil.DecodeHexNibble(text[position + 1]);
        if (hi < 0 || lo < 0) throw new ArgumentException("Expected two ASCII hex digits.", nameof(text));
        return (byte)((hi << 4) | lo);
    }

/**
     * Decodes a string generated by {@link #hexDump(byte[])}
     */
    public static byte[] DecodeHexDump(string hexDump)
    {
        ArgumentNullException.ThrowIfNull(hexDump);
        return DecodeHexDump(hexDump.AsSpan());
    }

/**
     * Decodes part of a string generated by {@link #hexDump(byte[])}
     */
    public static byte[] DecodeHexDump(string hexDump, int fromIndex, int length)
    {
        ArgumentNullException.ThrowIfNull(hexDump);
        CheckHexRange(hexDump.Length, fromIndex, length);
        return DecodeHexDump(hexDump.AsSpan(fromIndex, length));
    }

    /// <summary>Decodes ASCII hex pairs; whitespace, separators and prefixes are rejected.</summary>
    public static byte[] DecodeHexDump(ReadOnlySpan<char> hexDump)
    {
        if ((hexDump.Length & 1) != 0) throw new ArgumentException("The hex length must be even.", nameof(hexDump));
        if (hexDump.IsEmpty) return Array.Empty<byte>();
        byte[] result = new byte[hexDump.Length / 2];
        for (int i = 0; i < result.Length; i++) result[i] = DecodeHexByte(hexDump, i * 2);
        return result;
    }

/**
     * Returns a multi-line hexadecimal dump of the specified {@link ByteBuf} that is easy to read by humans.
     */
    public static string PrettyHexDump(ByteBuf buffer)
    {
        ArgumentNullException.ThrowIfNull(buffer);
        return PrettyHexDump(buffer, buffer.ReaderIndex, buffer.ReadableBytes);
    }

/**
     * Returns a multi-line hexadecimal dump of the specified {@link ByteBuf} that is easy to read by humans,
     * starting at the given {@code offset} using the given {@code length}.
     */
    public static string PrettyHexDump(ByteBuf buffer, int offset, int length)
    {
        var dump = new StringBuilder();
        AppendPrettyHexDump(dump, buffer, offset, length);
        return dump.ToString();
    }

/**
     * Appends the prettified multi-line hexadecimal dump of the specified {@link ByteBuf} to the specified
     * {@link StringBuilder} that is easy to read by humans.
     */
    public static void AppendPrettyHexDump(StringBuilder dump, ByteBuf buffer)
    {
        ArgumentNullException.ThrowIfNull(buffer);
        AppendPrettyHexDump(dump, buffer, buffer.ReaderIndex, buffer.ReadableBytes);
    }

/**
     * Appends the prettified multi-line hexadecimal dump of the specified {@link ByteBuf} to the specified
     * {@link StringBuilder} that is easy to read by humans, starting at the given {@code offset} using
     * the given {@code length}.
     */
    /// <remarks>Uses StringUtil.NEWLINE and preserves the pinned Java row-label rule:
    /// rows below 4096 are relative; later labels include the absolute buffer offset.
    /// Invalid, empty and released ranges are checked before modifying the builder.</remarks>
    public static void AppendPrettyHexDump(StringBuilder dump, ByteBuf buffer, int offset, int length)
    {
        ArgumentNullException.ThrowIfNull(dump);
        ArgumentNullException.ThrowIfNull(buffer);
        var reader = new SequenceReader<byte>(buffer.AsReadOnlySequence(offset, length));
        if (length == 0) return;
        dump.Append("         +-------------------------------------------------+")
            .Append(StringUtil.NEWLINE).Append("         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |")
            .Append(StringUtil.NEWLINE).Append("+--------+-------------------------------------------------+----------------+");
        Span<byte> bytes = stackalloc byte[16];
        int fullRows = length / 16;
        // Dump the rows which have 16 bytes.
        for (int row = 0; row < fullRows; row++)
        {
            reader.TryCopyTo(bytes); reader.Advance(16);
            // Per-row prefix.
            // Hex dump
            // ASCII dump
            AppendPrettyHexRow(dump, bytes, row, offset + row * 16);
        }
        // Dump the last row which has less than 16 bytes.
        int remainder = length & 15;
        if (remainder != 0)
        {
            reader.TryCopyTo(bytes[..remainder]);
            // Hex dump
            // Ascii dump
            AppendPrettyHexRow(dump, bytes[..remainder], fullRows, offset + fullRows * 16);
        }
        dump.Append(StringUtil.NEWLINE).Append("+--------+-------------------------------------------------+----------------+");
    }

    /* Separate class so that the expensive static initialization is only done when needed */
    // CLR: BCL conversion and computed row padding replace HexUtil and its Java lookup tables.
    private static void AppendPrettyHexRow(StringBuilder dump, ReadOnlySpan<byte> bytes, int row, int absoluteIndex)
    {
        // Generate the lookup table for the start-offset header in each row (up to 64KiB).
        // CLR: preserve the cached-vs-fallback label rule without caching row strings.
        int label = row < 4096 ? row * 16 : absoluteIndex;
        dump.Append(StringUtil.NEWLINE).Append('|').Append(label.ToString("x8", CultureInfo.InvariantCulture)).Append('|');
        // Generate the lookup table for byte-to-hex-dump conversion
        foreach (byte value in bytes) dump.Append(' ').Append(StringUtil.ByteToHexStringPadded(value));
        // Generate the lookup table for hex dump paddings
        dump.Append(' ', (16 - bytes.Length) * 3).Append(" |");
        // Generate the lookup table for byte-to-char conversion
        foreach (byte value in bytes) dump.Append(value is >= 32 and <= 126 ? (char)value : '.');
        // Generate the lookup table for byte dump paddings
        dump.Append(' ', 16 - bytes.Length).Append('|');
    }

    private static void CheckHexRange(int capacity, int index, int length)
    {
        if (index < 0 || length < 0 || index > capacity - length)
            throw new ArgumentOutOfRangeException(nameof(index));
    }
}
