/*
 * Copyright 2016 The Netty Project
 *
 * The Netty Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.ExceptionServices;
using System.Threading;

namespace Netty.NET.Common.Internal;

public static class ThrowableUtil
{
    // CLR adaptation: Exception has no suppressed-exception field. Weak keys retain identity and avoid leaks.
    private static readonly ConditionalWeakTable<Exception, List<Exception>> Suppressed = new ConditionalWeakTable<Exception, List<Exception>>();
    /**
     * Set the {@link StackTraceElement} for the given {@link Throwable}, using the {@link Class} and method name.
     */
    public static T unknownStackTrace<T>(T cause, Type clazz, string method) where T : Exception
    {
        ObjectUtil.checkNotNull(cause, "cause");
        ObjectUtil.checkNotNull(clazz, "clazz");
        // CLR permits assigning a remote trace only before an exception has been thrown.
        if (cause.StackTrace == null) ExceptionDispatchInfo.SetRemoteStackTrace(cause, "   at " + clazz.FullName + "." + method + " (Unknown Source)");
        return cause;
    }
    // CLR factory compatibility overload retains the caller's source location.
    public static T unknownStackTrace<T>(Func<string, T> factory, Type clazz,
        [CallerMemberName] string method = "", [CallerFilePath] string file = "", [CallerLineNumber] int line = 0) where T : Exception
    {
        return unknownStackTrace(factory("location: " + clazz.Name + "::" + method + "() in " + file + ":" + line), clazz, method);
    }
    /**
     * Gets the stack trace from a Throwable as a String.
     *
     * @param cause the {@link Throwable} to be examined
     * @return the stack trace as generated by {@link Throwable#printStackTrace(java.io.PrintWriter)} method.
     */
    [Obsolete]
    public static string stackTraceToString(Exception cause)
    {
        // CLR exception text includes its type, message, inner exception and stack trace.
        // Rendering to a string needs no stream whose disposal can fail.
        // ignore as should never happen
        return ObjectUtil.checkNotNull(cause, "cause").ToString();
    }
    [Obsolete]
    public static bool haveSuppressed() => true;
    public static void addSuppressed(Exception target, Exception suppressed)
    {
        if (suppressed == null) return;
        ObjectUtil.checkNotNull(target, "target");
        if (ReferenceEquals(target, suppressed)) throw new ArgumentException("Self-suppression not permitted", nameof(suppressed));
        var list = Suppressed.GetValue(target, _ => new List<Exception>());
        lock (list) list.Add(suppressed);
    }
    public static void addSuppressedAndClear(Exception target, List<Exception> suppressed)
    {
        addSuppressed(target, suppressed);
        suppressed.Clear();
    }
    public static void addSuppressed(Exception target, List<Exception> suppressed)
    {
        foreach (Exception error in suppressed) addSuppressed(target, error);
    }
    public static Exception[] getSuppressed(Exception source)
    {
        ObjectUtil.checkNotNull(source, "source");
        if (!Suppressed.TryGetValue(source, out var list)) return Array.Empty<Exception>();
        lock (list) return list.ToArray();
    }
    /**
     * Capture the stack trace of the given thread, interrupt it, and attach the stack trace as a suppressed exception
     * to the given cause.
     * @param thread The thread to interrupt.
     * @param cause The cause to attach a stack trace to.
     */
    public static void interruptAndAttachAsyncStackTrace(Thread thread, Exception cause)
    {
        ObjectUtil.checkNotNull(thread, "thread");
        ObjectUtil.checkNotNull(cause, "cause");
        System.Threading.ThreadState state = thread.ThreadState;
        // CLR exposes a managed stack for the current thread only. For other threads retain the observed
        // state and mark stack unavailability in the diagnostic rather than attributing this caller's stack.
        string trace = ReferenceEquals(thread, Thread.CurrentThread) ? new StackTrace().ToString() : "Managed stack of another thread is unavailable through System.Threading.Thread.";
        var asyncIE = new ThreadInterruptedException("Asynchronous interruption: " + thread + " (" + state + ')');
        thread.Interrupt();
        ExceptionDispatchInfo.SetRemoteStackTrace(asyncIE, trace);
        addSuppressed(cause, asyncIE);
    }
}
