using System;
using Netty.NET.Common.Internal;

namespace Netty.NET.Common.Tests.Porting;

// Expected values were generated by javac/java from the pinned original
// PlatformDependent.hashCodeAsciiSafe/get*Safe and PlatformDependent0 compute/
// sanitize method bodies, for both native byte orders. No C# implementation
// was used to calculate this independent reference.
public class AsciiStringHashContractTest
{
    [Fact]
    public void EveryTailLengthAndWordBoundaryMatchesThePinnedJavaHash()
    {
        int[] expected = BitConverter.IsLittleEndian ? LittleEndian : BigEndian;
        for (int length = 0; length <= 64; length++)
        {
            byte[] bytes = new byte[length + 22];
            for (int i = 0; i < bytes.Length; i++)
                bytes[i] = unchecked((byte)(i * 73 + length * 17 + 128));
            AsciiString view = new AsciiString(bytes, 11, length, false);
            Assert.Equal(expected[length], view.GetHashCode(), "length=" + length);
            Assert.Equal(expected[length], PlatformDependent.HashCodeAsciiSafe(bytes, 11, length), "length=" + length);
            Assert.Equal(expected[length], AsciiString.HashCode(new StringCharSequence(view.ToString())), "length=" + length);
        }
    }
    private static readonly int[] LittleEndian =
    {
        -1028477387, -1008832551, -1008828982, -1688233504, -973635636, -293533976, -850185371, 1387177765,
        277172517, -161519911, 1710229042, 1114611064, -1057651612, -803035280, 887391685, -945864603,
        -1389922059, 1601536793, 87059898, 164111600, -1117412516, -203114472, 1215757285, 852459269,
        -1303702875, -1583695815, 1658003810, -1040686744, -786061644, 1474756672, -1860813979, 1614190949,
        -752319179, 569649753, 1967469546, -807491584, -435397940, -1620948888, 1125667269, 617048901,
        -1735473115, -268274343, 1398252114, 1593992600, -407089308, -857010960, -167221723, 1757900421,
        -2001162251, -1078506087, 1199396826, 283928336, -1086038436, -877958760, -1472186811, 1361131301,
        647227813, 1358583481, -876433022, -883778168, 633098676, -910731840, -2099415099, -82314363,
        -2096030667,
    };
    private static readonly int[] BigEndian =
    {
        -1028477387, -1008832551, -1008831277, -1688227639, -890337081, -747106301, 153678731, -105033991,
        205010825, -580763523, -2135392001, -1851948627, -1109465341, 664829335, -1612172489, 198319493,
        -1881327363, -2089136735, 877752139, -1477435279, -453858561, -389643381, 1271897539, 794163825,
        -611635791, -630693115, 1078242583, 1729501461, -1913442181, -691447201, -1849931089, 1683067773,
        2128257637, -1980442999, -1086922461, 399092345, 1866452471, 75643667, 1750049147, -259510871,
        670633657, 1081028141, -1464310193, 120260189, -1968273613, 33701287, -1867977689, -353919179,
        -899327187, 1530393169, 2037349787, -1163511775, 737787439, -1040856933, 116642227, -1048897759,
        -493677855, 2142629557, 1043387495, 485989317, 900890283, 261903471, 1578264991, -1946143955,
        -1672891755,
    };
}
